@startuml SSD4

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative 4 - Member tries to downvote a previously downvote post

autonumber

actor "Member" as Member
participant "System" as System

activate Member

    Member -> System: Clicks downvote arrow on a previously downvoted post
    activate System

        System --> Member: Doesn't validate the vote
        deactivate System

deactivate Member

@enduml
