@startuml SSD1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative 1 - Sort posts by Unpopular

autonumber

actor "Visitor" as Visitor
participant "System" as System

activate Visitor

    Visitor -> System: Clicks on "Unpopular" in the feed
    activate System

        System --> Visitor : Displays the lowest scored posts
        deactivate System

deactivate Visitor

@enduml