name: JMeter Test

on:
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install jq
        run: sudo apt-get install jq

      - name: Set environment
        run: cp .env.template .env

      - name: Start containers
        run: docker-compose up --detach

      - name: Setup dev
        run: npm run setup:dev

      - name: Setup public
        run: |
          export CI=false
          npm run build:public

      - name: Start backend
        run: npm run start:dev &

      - name: Start frontend
        run: BROWSER=none npm run start:public &

      - name: Wait a little
        run: sleep 10

      - name: Setup JMeter
        run: npm run setup:jmeter

      - name: Run tests for 10 users and Check Throughput
        run: |
              chmod +x ./.github/workflows/throughputReference.sh
              ./.github/workflows/throughputReference.sh 10

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results-10Users-${{ github.run_number }}-${{ github.run_id }}
          path: /home/runner/work/switch-qa-23-project-switch-qa-23-2/switch-qa-23-project-switch-qa-23-2/report
          if-no-files-found: warn

      - name: Run tests for 50 users and Check Throughput based on 10 users value
        run: |
          chmod +x ./.github/workflows/throughputCheck.sh
          ./.github/workflows/throughputCheck.sh 50

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results-50Users-${{ github.run_number }}-${{ github.run_id }}
          path: /home/runner/work/switch-qa-23-project-switch-qa-23-2/switch-qa-23-project-switch-qa-23-2/report
          if-no-files-found: warn

      - name: Run tests for 100 users and Check Throughput based on 10 users value
        run: |
          chmod +x ./.github/workflows/throughputCheck.sh
          ./.github/workflows/throughputCheck.sh 100

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results-100Users-${{ github.run_number }}-${{ github.run_id }}
          path: /home/runner/work/switch-qa-23-project-switch-qa-23-2/switch-qa-23-project-switch-qa-23-2/report
          if-no-files-found: warn

      - name: Run tests for 150 users and Check Throughput based on 10 users value
        run: |
          chmod +x ./.github/workflows/throughputCheck.sh
          ./.github/workflows/throughputCheck.sh 150

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results-150Users-${{ github.run_number }}-${{ github.run_id }}
          path: /home/runner/work/switch-qa-23-project-switch-qa-23-2/switch-qa-23-project-switch-qa-23-2/report
          if-no-files-found: warn

      - name: Run tests for 200 users and Check Throughput based on 10 users value
        run: |
          chmod +x ./.github/workflows/throughputCheck.sh
          ./.github/workflows/throughputCheck.sh 200

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results-200Users-${{ github.run_number }}-${{ github.run_id }}
          path: /home/runner/work/switch-qa-23-project-switch-qa-23-2/switch-qa-23-project-switch-qa-23-2/report

      - name: Dynamic Users Loop and Check Throughput based on 10 users value
        run: |
          chmod +x ./.github/workflows/loopAction.sh
          ./.github/workflows/loopAction.sh 250

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results-DynamicUsersLoopResults-${{ github.run_number }}-${{ github.run_id }}
          path: /home/runner/work/switch-qa-23-project-switch-qa-23-2/switch-qa-23-project-switch-qa-23-2/report

